#ifndef BOARD_CONFIG_H
#define BOARD_CONFIG_H

#include <avr/io.h>

#define MOVEMENT_LED_DDR DDRD
#define MOVEMENT_LED_PORT PORTD
#define MOVEMENT_LED_PIN PD2

#define DOOR_OPENING_LED_DDR DDRD
#define DOOR_OPENING_LED_PORT PORTD
#define DOOR_OPENING_LED_PIN PD3

#define DOOR_CLOSING_LED_DDR DDRD
#define DOOR_CLOSING_LED_PORT PORTD
#define DOOR_CLOSING_LED_PIN PD4

#define OBSTACLE_LED_DDR DDRD
#define OBSTACLE_LED_PORT PORTD
#define OBSTACLE_LED_PIN PD5

#define BUZZER_DDR DDRB
#define BUZZER_PORT PORTB
#define BUZZER_PIN PB1

#endif