#ifndef ELEVATOR_PROTOCOL_H
#define ELEVATOR_PROTOCOL_H

#define ELEVATOR_I2C_ADDRESS (0b1010111)

#define ELEVATOR_CMD_ALL_OFF        '0'
#define ELEVATOR_CMD_MOVING         'M'
#define ELEVATOR_CMD_DOOR_OPENING   'O'
#define ELEVATOR_CMD_DOOR_CLOSING   'C'
#define ELEVATOR_CMD_OBSTACLE       'X'
#define ELEVATOR_CMD_BUZZER_STOP    'S'

#endif